name: CI

on:
- push
- pull_request

jobs:
  linters:
    name: ubuntu-latest-linters
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e '.[dev]'
    - name: Analysing the code with black
      run: |
        black --check .
    - name: Analysing the code with flake8
      run: |
        flake8

  unit_tests:
    needs:
      - linters
    runs-on: ubuntu-latest
    name: ubuntu-latest-tests-python${{ matrix.python-version}}
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e '.[dev]'
    - name: Invoke PyTest
      run: |
        pytest .
